### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TongDaDa** [akavel/rsrc#22]
[ERROR]	Update failed for github.com/skratchdot/open-golang: github.com/skratchdot/open-golang contains uncommitted changes. Skipping update
[ERROR]	Update failed for github.com/ivaxer/go-xattr: github.com/ivaxer/go-xattr contains uncommitted changes. Skipping update
[ERROR]	Update failed for github.com/akavel/rsrc: github.com/akavel/rsrc contains uncommitted changes. Skipping update
[ERROR]	Failed to checkout packages: github.com/skratchdot/open-golang contains uncommitted changes. Skipping update

**Comment by akavel** [comment]
This looks like something completely unrelated to rsrc. I suggest you ask somebody in your work team to help you resolve this.
