### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by StephanVerbeeck** [akavel/rsrc#23]
Build is not working (neither by hand "go get ..." nor by provided build batch file)

	C:\Build\Go_tools\rsrc>buildcross.bat
		rsrc_windows_386.exe
		rsrc.go:13:2: use of internal package github.com/akavel/rsrc/internal not allowed
		rsrc_windows_amd64.exe
		rsrc.go:13:2: use of internal package github.com/akavel/rsrc/internal not allowed

**Comment by akavel** [comment]
Hm, you don't seem to be building in GOPATH. If you're using Go 1.11 or later (you can check that with `go version`), try to run the following command before `buildcross.bat`, it might help:

```
go mod init
```

**Comment by akavel** [comment]
Based on a [comment you seem to have made](https://github.com/akavel/rsrc/issues/5#issuecomment-467844658) in a different thread since, I assume it's working now for you, so I'm closing this issue. If not, please reopen or add a comment with appropriate info.
