### ISSUE TITLE
Can icon be externalize from .rsrc section and not part of the signature ?

### ISSUE THREAD

**Issue by iradization** [akavel/rsrc#25]
Hi,

I was wondering if there's a way to somehow externalize the .rsrc section from the pe file, so it's not be part of the signature.

Perhaps do you know of a way to specify an external path of a valid .ico file anywhere in the PE file ? maybe there's an API for this ? My goal is to be able to switch icons for an already existing signed file, instead of embedding each icon in a separated file and sign it with this specific embedded icon. 

I've read the documentation of the manifest embedded xml inside the .rsrc, but couldn't find and configuration do so ...

thanks !

**Comment by akavel** [comment]
Hi,

I'm afraid I have no idea, I'm sorry! The rsrc app is only for Go applications, and only before they are compiled yet.
