### ISSUE TITLE
arm build failes

### ISSUE THREAD

**Issue by Niondir** [akavel/rsrc#27]
If the generates .syso file is next to the binary, an arm build failes. Is there any workaround? e.g. to tell the go compiler to not use the syso file on arm builds?

**Comment by akavel** [comment]
Ehhh, *reeeally* sorry for responding so late, I kinda can't get myself to do anything with rsrc nowadays :/ (I put it in the ["code shelter"](https://www.codeshelter.co/) but nobody seemed to pick it up either...) So, back to the matter:

I believe if you add a suffix to the file name, like renaming your original file to `foo_amd64.syso`, it won't get picked by arm (or any other non-amd64) builds... you can probably even make it `foo_windows_amd64.syso`... I really should have put it long ago in the readme & --help, but unfortunately, as I mentioned above, I can't make myself work on rsrc for long time already...

**Comment by Niondir** [comment]
Thanks a lot, it works with `_windows` prefix. It should really get into the readme!
