### ISSUE TITLE
Go Get Fails due to undefined : pe.IMAGE_FILE_MACHINE_ARMNT

### ISSUE THREAD

**Issue by otmos** [akavel/rsrc#30]
![image](https://user-images.githubusercontent.com/43470049/92233280-e9578e80-eea7-11ea-978f-5a7c74c5293c.png)

**Comment by akavel** [comment]
This const [was added in Go 1.12](https://github.com/golang/go/commit/18034e6b9f0f623335e6358e0a4634a4eec04dd1), so I assume you're most probably using an old version of Go. I suggest you either upgrade Go, or use an older version of rsrc (from [before rsrc introduced experimental support for ARMNT](https://github.com/akavel/rsrc/commit/5f0b068a155dd09e4723ceebfad5f58d1693c4a5), for example v0.8.0).

**Comment by 8zbc** [comment]
> This const [was added in Go 1.12](https://github.com/golang/go/commit/18034e6b9f0f623335e6358e0a4634a4eec04dd1), so I assume you're most probably using an old version of Go. I suggest you either upgrade Go, or use an older version of rsrc (from [before rsrc introduced experimental support for ARMNT](https://github.com/akavel/rsrc/commit/5f0b068a155dd09e4723ceebfad5f58d1693c4a5), for example v0.8.0).

Dear akvel,

Yes, you are right, I was using 1.11 at that time, I saw the the message that it needed 1.12 at the bottom of the message which i didn't show it here. but only noticed it later, so I have upgraded to 1.14. thanks for your reply and helping out. it is working now.

 cheers.
