### ISSUE TITLE
coff/coff.go error @line 133 & line 220 when trying to download the whole repo.

### ISSUE THREAD

**Issue by 8zbc** [akavel/rsrc#33]
Hi Akavel,

I am trying to download with this go command on linux and receive the following errors. wonder what could went wrong here? 
 
jay@localhost:~/go/src/test> go get -u github.com/akavel/rsrc
# github.com/akavel/rsrc/coff
../../pkg/mod/github.com/akavel/rsrc@v0.10.1/coff/coff.go:133:18: undefined: pe.IMAGE_FILE_MACHINE_ARMNT
../../pkg/mod/github.com/akavel/rsrc@v0.10.1/coff/coff.go:220:7: undefined: pe.IMAGE_FILE_MACHINE_ARMNT
note: module requires Go 1.12jay@localhost:~/go/src/test> 
jay@localhost:~/go/src/test> 

your code @ 
line 133 is =  coff.Machine pe.IMAGE_FILE_MACHINE_ARMNT:
line 220 is =  case pe.IMAGE_FILE_MACHINE_ARMNT:

My PC is AMD64, so is there any way to skip the ARM arch for me? I run this through script, so I did't download the entire source code and compile.

Please advise. thanks in advance.

**Comment by akavel** [comment]
You're most probably using too old Go. You need Go 1.12 or newer. Check out what shows up when you run `go version`. See also: #30 .

**Comment by 8zbc** [comment]
got it, thanks

Mateusz Czapliński <notifications@github.com> 于2020年12月23日周三 上午4:22写道：
