### ISSUE TITLE
Unable to compile in linux with two errors.

### ISSUE THREAD

**Issue by 8zbc** [akavel/rsrc#34]
Dear @akavel ,

I am having difficulties to compile the rsrc. first off, I download the complete codes. with git clone, then place into linux folder as follow. /go/src/github.com/akavel/rsrc

_jay@localhost:~/go/src/github.com/akavel/rsrc> sudo go build
[sudo] password for root: 
go build: build output "rsrc" already exists and is a directory
jay@localhost:~/go/src/github.com/akavel/rsrc> sudo go build
go: finding module for package github.com/akavel/rsrc/rsrc
rsrc.go:8:2: no matching versions for query "latest"
jay@localhost:~/go/src/github.com/akavel/rsrc>_ 

there has been existing subfolder name called rsrc, and hence the error 
go build: build output "rsrc" already exists and is a directory
after I move away the subfolder, it gave me another error.
rsrc.go:8:2: no matching versions for query "latest"

which i have no idea how to solve it, please advise. thanks

my platform: opensuse 15.2, AMD64

**Comment by akavel** [comment]
I'm really sorry, but that's a generic beginner Go question, not especially related to rsrc library - and unfortunately I currently don't have enough time available to be able to mentor you through beginner Go learning stages. Given that, the best I can think of that I can do for you, is to recommend that you try to find some beginner-friendly Go language community/forum, and ask people there for help with your problems. I'm not very active in Go communities currently, so I'm not sure what are the best places for that, still there's at least two ways I'd recommend to maybe try first:

- https://golang.org/help/ - here you can find a list of various communities; I would recommend you try your luck with as many of them as possible and be as kindly and gracefully persistent as you are here with me; given enough patience, sooner or later you should be able to stumble upon someone with enough time at their hands to be able to help and mentor you
- you could also try searching the internet with keywords similar to 'golang forum', 'golang beginner forum', and/or some variations of that - you might possibly be able to find some more venues not listed on the "official" Golang.org website's list; for example, one more community I don't seem to currently see listed there is the https://www.reddit.com/r/golang subreddit.
- regardless of the above, I'd also recommend reading (and rereading as many times as you have patience) through the documentation listed at https://golang.org/doc/ - personally, that's how *I* mostly learnt Go, though I fully understand there are different people with different personalities and it's not the way that will work for everyone. 

Again, I'm sorry I won't help you more, and wish you all the best and good luck with learning Go and having fun with it! Hope you'll find some help through the channels above, and maybe we'll meet one day again once you have questions or suggestions that are more specific to rsrc or some other of my projects in particular! :)

Have a great time and be awesome!

**Comment by 8zbc** [comment]
@akavel, thanks for reply here, I just not sure if it is code issue or the the compiler issue at first, since now you have pointed out it is the go lang issue, I will consult the online links that you have provided, thanks again for pointing me towards the right directions, Merry Christmas and Happy Holiday, Cheers.
