### ISSUE TITLE
Can this library be used under linux

### ISSUE THREAD

**Issue by hanxiaohuivc** [akavel/rsrc#40]
Can this library be used under linux
Hello. Can I use rsrc under linux? How to use it? I generated the syso file, but the executable icon didn't change. thanks.

**Comment by servusdei2018** [comment]
@hanxiaohuivc as I understand it, this tool is to change the _Windows_ manifest and icon. You can use Go on linux to make an exe, and rsrc on linux to give it an icon and change its manifest, but rsrc is for Windows exe's and not linux ones.

On linux, you typically have a [.desktop file](https://www.maketecheasier.com/create-desktop-file-linux/), which is independent of your actual program, and that is how you add an icon to your program.

**Comment by hanxiaohuivc** [comment]
> 

Yes. Only .desktop files can be used under linux. thanks.

**Comment by ChugunovRoman** [comment]
@servusdei2018 Hi, I know the Go automatically embeded *.syso files when I build an app, but why this does not happens when I build app for Windows on Linux?

**Comment by servusdei2018** [comment]
@ChugunovRoman as far as I know, *.syso files are embedded too when you build for Windows on Linux. Probably your *.syso file is misconfigured though, you might have better luck with the [syso](https://github.com/hallazzang/syso) utility. If that still doesn't work, I recommend asking on the Golang discord: https://discord.com/invite/golang
