### ISSUE TITLE
How can I get program running log?

### ISSUE THREAD

**Issue by nihility23** [akavel/rsrc#44]
I can get log at terminal before getting administrator permission. But after I get administrator permission, a terminal flashback and I can't get any log. How can I do?
Example below:
1.Getted permission
![微信截图_20230309152102](https://user-images.githubusercontent.com/14112926/223949751-37494118-bd5d-40a5-9213-05c300a2009f.png)
2.Not Getted permission
![微信截图_20230309152221](https://user-images.githubusercontent.com/14112926/223949797-147b932b-0037-4408-8dcb-4e7dafcd9b65.png)

**Comment by servusdei2018** [comment]
@wocan23 is rservice one of your personal projects? It doesn't appear to have anything to do with this repository.
