### ISSUE TITLE
when i use https://github.com/lxn/walk , how to use walk.NewIconFromResource

### ISSUE THREAD

**Issue by shnmng** [akavel/rsrc#5]
I want to know when i embed a icon to *.syso file , when i use it on walk ,like this
walk.NewIconFromResource("xxx")
what is the xxx ?

**Comment by StephanVerbeeck** [comment]
2 steps needed for setting the same application Icon also on all GUI windows
	
	var appIcon, _ = walk.NewIconFromResourceId(3) // number 3 is resource ID printed by RSRC.exe while making .syso file
	
	MainWindow{
		Title:    "YourApplication",
		Name:     "MainWindow",
		AssignTo: &mainWindow,
		Icon:     appIcon,
		MinSize:  Size{600, 400},
		Size:     Size{1024, 640},
		Layout:   HBox{MarginsZero: true},
		...

**Comment by lxn** [comment]
You can also do it like this: `Icon: 3,` or `Icon: "foo",`.
